In [1]:
import numpy as np
import pandas as pd
from transformers import pipeline

import nltk
# nltk.download('vader_lexicon')

import pandas as pd
# from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [2]:
df = pd.read_csv("../data/preprocessing/preprocessing_data.csv")
df.head()

,title,stars,text
0,Pantai Tanjung Gelam,5,NaN
1,Pantai Tanjung Gelam,5,pantai menakjubkan pasirpasir putih good
2,Pantai Tanjung Gelam,5,pantai tanjung gelam merupakan salah satu pant...
3,Pantai Tanjung Gelam,5,salah satu pantai favorit bila karimunjawa ber...
4,Pantai Tanjung Gelam,5,pantai denganpasir putih bersih panorama laut ...

In [3]:
df['text']

0                                                    NaN
1               pantai menakjubkan pasirpasir putih good
2      pantai tanjung gelam merupakan salah satu pant...
3      salah satu pantai favorit bila karimunjawa ber...
4      pantai denganpasir putih bersih panorama laut ...
                             ...
715                                             stunning
716      nice place for sunrise and hangout with friends
717    depending on when you come and wind direction ...
718    destinasi sangat bagus pengamatan sun rise jal...
719                                         pantai indah
Name: text, Length: 720, dtype: object

In [4]:
df = df.dropna()

In [5]:
# Pakai GPU
classifier = pipeline("sentiment-analysis", model="w11wo/indonesian-roberta-base-sentiment-classifier", device=-1)

# Batch prediction
batch_size = 64
hasil_label = []

for i in range(0, len(df), batch_size):
    teks_batch = df['text'].iloc[i:i+batch_size].tolist()
    pred_batch = classifier(teks_batch)
    hasil_label.extend([x['label'] for x in pred_batch])

df['sentimen_bert'] = hasil_label

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [6]:
# Inisialisasi VADER
# removed vader logic

# Fungsi klasifikasi sentimen dengan VADER

# Terapkan ke kolom cleaned_text
df['sentimen'] = df['sentimen_bert'] # Set sentimen utama menjadi hasil IndoBERT

In [7]:
df

,title,stars,text,sentimen_bert,sentimen
1,Pantai Tanjung Gelam,5,pantai menakjubkan pasirpasir putih good,positive,positive
2,Pantai Tanjung Gelam,5,pantai tanjung gelam merupakan salah satu pant...,positive,positive
3,Pantai Tanjung Gelam,5,salah satu pantai favorit bila karimunjawa ber...,positive,positive
4,Pantai Tanjung Gelam,5,pantai denganpasir putih bersih panorama laut ...,positive,positive
5,Pantai Tanjung Gelam,5,the iconic tanjung gelam coconut trees,positive,positive
...,...,...,...,...,...
715,Pantai Legon Lele,4,stunning,negative,negative
716,Pantai Legon Lele,5,nice place for sunrise and hangout with friends,positive,positive
717,Pantai Legon Lele,3,depending on when you come and wind direction ...,positive,positive
718,Pantai Legon Lele,5,destinasi sangat bagus pengamatan sun rise jal...,positive,positive
719,Pantai Legon Lele,4,pantai indah,positive,positive

In [8]:
df.to_csv('../data/labelling/label_data.csv', index=False)