In [1]:
import pandas as pd
import re
import seaborn as sns
import matplotlib.pyplot as plt
from IPython.display import display

In [2]:
df = pd.read_csv("../data/cleaning/clear_data.csv")
df.head()

,title,stars,text
0,Pantai Tanjung Gelam,5,NaN
1,Pantai Tanjung Gelam,5,pantai yang menakjubkan dengan pasirpasir puti...
2,Pantai Tanjung Gelam,5,pantai tanjung gelam merupakan salah satu pant...
3,Pantai Tanjung Gelam,5,salah satu pantai favorit bila ke karimunjawa ...
4,Pantai Tanjung Gelam,5,pantai denganpasir putih yang bersih panorama ...

#Normalisasi

In [3]:
norm = {
    'bnr': 'benar', 'yg': 'yang', 'thn': 'tahun', 'wk': ' ', 'bpk': 'bapak',
    'lg': 'lagi', 'kyk': 'kayak', 'mkan': 'makan', 'bljr': 'belajar', 'mikir2': 'mikir',
    'siaaapp': 'siap', 'okaayy': 'oke', 'org': 'orang', 'one': 'satu', 'dg': 'dengan',
    'lali': 'lupa', 'pntai': 'pantai', 'htm': 'biaya', 'enk': 'enak', 'mntap': 'mantap', 'g': 'gak', 'cantikkkk ': 'cantik', 'buaguussss': 'bagus', 'bgttttt': 'banget', 'mjd': 'menjadi'
}

def normalisasi(str_text):
    if not isinstance(str_text, str):
        return str(str_text)
    for i in norm:
        str_text = re.sub(r'\b' + re.escape(i) + r'\b', norm[i], str_text)
    return str_text

df['text'] = df['text'].apply(lambda x: normalisasi(x))
df

,title,stars,text
0,Pantai Tanjung Gelam,5,nan
1,Pantai Tanjung Gelam,5,pantai yang menakjubkan dengan pasirpasir puti...
2,Pantai Tanjung Gelam,5,pantai tanjung gelam merupakan salah satu pant...
3,Pantai Tanjung Gelam,5,salah satu pantai favorit bila ke karimunjawa ...
4,Pantai Tanjung Gelam,5,pantai denganpasir putih yang bersih panorama ...
...,...,...,...
715,Pantai Legon Lele,4,stunning
716,Pantai Legon Lele,5,nice place for sunrise and hangout with friends
717,Pantai Legon Lele,3,depending on when you come and wind direction ...
718,Pantai Legon Lele,5,destinasi yang sangat bagus untuk pengamatan s...
719,Pantai Legon Lele,4,pantai yang indah

#Stopwords

In [4]:
import Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary

more_stop_words = []

stop_words = StopWordRemoverFactory().get_stop_words()
stop_words.extend(more_stop_words)

new_array = ArrayDictionary(stop_words)
stop_words_remover_new = StopWordRemover(new_array)

def stopword(str_text):
    str_text = stop_words_remover_new.remove(str_text)
    return str_text

df['text'] = df['text'].apply(lambda x: stopword(x))
df.head()

,title,stars,text
0,Pantai Tanjung Gelam,5,nan
1,Pantai Tanjung Gelam,5,pantai menakjubkan pasirpasir putih good
2,Pantai Tanjung Gelam,5,pantai tanjung gelam merupakan salah satu pant...
3,Pantai Tanjung Gelam,5,salah satu pantai favorit bila karimunjawa ber...
4,Pantai Tanjung Gelam,5,pantai denganpasir putih bersih panorama laut ...

#Tokenize

In [5]:
tokenized = df['text'].apply(lambda x:x.split())
tokenized.head()

0                                                [nan]
1       [pantai, menakjubkan, pasirpasir, putih, good]
2    [pantai, tanjung, gelam, merupakan, salah, sat...
3    [salah, satu, pantai, favorit, bila, karimunja...
4    [pantai, denganpasir, putih, bersih, panorama,...
Name: text, dtype: object

#Stemming

In [6]:

print("DataFrame 'df' has been saved to '../data/preprocessing/preprocessing_data.csv'")

DataFrame 'df' has been saved to '../data/preprocessing/preprocessing_data.csv'

In [7]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def stemming(text_cleaning):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()
    do = []
    for w in text_cleaning:
        dt = stemmer.stem(w)
        do.append(dt)
    d_clean = " ".join(do)
    print(d_clean)
    return d_clean

tokenized = tokenized.apply(stemming)
tokenized.to_csv('../data/preprocessing/preprocessing_data.csv', index=False)

nan
pantai takjub pasirpasir putih good

pantai tanjung gelam rupa salah satu pantai paling indah karimunjawa pasir putih halus air laut sangat jernih gradasi warna biru tenang suasana cocok santa renang foto sunset pantai sangat kenal memang luar biasa indah akses tuju lokasi cukup mudah sudah warungwarung sederhana tempat wajib kunjung libur karimunjawapantai cocok bawa anak renang area dangkal luasbisa sewa watersport banana boatjetskidll

salah satu pantai favorit bila karimunjawa dekat pantai lain sunset beach pantai batu topengdi pantai tanjung gelam bisa dapat spot sunset dapat spot favorit foto pohon kelapa tumbuh miring jorok laut
pantai denganpasir putih bersih panorama laut biru sedap pandang mata spot sunset pesona

the iconic tanjung gelam coconut trees
maleman saking gak move on nya

biaya 10kview sunset bagus
tempat nyunset estetik karimunjawa
pantai nya keren

watcouttt theres a jetski cheating

pantai pandang ciamik banget sunset masuk 5rb orang cuman jalan kecil pake motor aja main cano cuman 50rb

pantainyaa baguss akses jalan mudahh cuman gelap aja dikit view sunsetnya cakepp main kano jetski sewa drone di pinggir pantai banyak warung2 jadi makan kalo laper wkwk

kesini lihat sunset antri foto kelapa miring panjangbanyk warung kelapa muda enak joss mantab buah besar2

spot foto sedang cari sunset paling ciamik bagus bangetpasir nya putih bersih pohon kelapa miring rela antri buat dapetin hasil foto view bagus
best spot sunset sih tempat

part of karimun jawa island and this place most beautiful everywhere you see w view sunset

baguus banget pantai icon pohon kelapa lengkung jadi unik utk foto2 biaya idr 10000 pasir bagus lembutenak jg buat renang lihat sunset
amazing karimunjawa island

pantai pohon kelapa miringdan sunset bagus

a nice place to enjoy the sunset
identik kelapa miring sama sunsetnya besttt banget

best place to chill because theres a lot of trees
kelapa mahal

pantai buat nikmat sunsettapi pas kesini pagi jadi ga sunset deh

sunrise sunset karimun emg gaperlu raguin tp kalo sini sunset nya cantikbgttttt

very commercialized beach a lot of activities and food are available of course they all come with a price food and drinks are more expensive than in town entrance tickets are 10k toilets are mostly broken so better pee in the sea
maasyaa allooh alhamdulillaah msh asri

nyaman air jernih pagi banyak pengunjungmenyediakan beberapa wahana renang pantai jetski banana boat rolling donuts kano

keren pantai pohon kelapa miring iconic biasa pakai orang2 foto manjat gitu cuman kalo kesini pas rame orang mau foto pohon kelapa mesti antri tp bagus hasil

makasimalkn perancanaan utama umkm tempat
indah sekali

une plage trs agrable avec mme des poissons en snorkelingpouf confortable avec les consommations pas chres accs en scooter parasol musique le soir trs convivial
kalau mau nikmat sunset yah sini

pantai nan eksotis karimunjawa batu karang pasir putih sangat landai ombak kecil spot nikmat sunset renang main banana boat naik perahu jemur dar main pasir cocok libur sama teman keluarga
spot sunset

pantai wajib kalo karimun jawa wkwk spot foto kelapa miring bekas ratus ribu umat

pantai cocok lihat sunset jarak lumayan jauh pusat kota jalan tuju pantai sepi turun jangan terlalu lama pantai telah matahari tenggelam jalan jadi gelap sekali pasir putih lembut sekali pandang bagus 2 pohon kelapa legendnya sini banyak warung sedia goreng minum mie kelapa muda

pantai ujung gelam karimunjawa sangat bagus sekali cocok untuj lihat sunset matahari tenggelam jadi kalau sore sangat ramai pantai nya smbersih banyak jual minum makan banyak main jetsky perhau foto drone sangat bagus spot foto
bagus banget alloh ken kesana ngga zonk sama sekali

i couldnt say it was the worst but it was bad you had to pay for the entry there was plastic but the part that i did like was the swings

sehr ruhig und schn leider auch sehr abgelegen mit auto oder moped zu erreichen ist bei einheimischen sehr beliebt

pantai kagum bersih nyamanbanyak spot foto menarikcocok acara sendiri maupun family ghateringyg mau d karimun wajib banget pantai bobby
nikmat kopi

sunrisenya cakepp angin sepoysepoy sini juga suasa enak sunyiii pagipagi bengong sini ngopi enak ini
sunrise pantai bobby karimunjawa keren banget pantai bagus fasilitas jg cukup tarik

salah satu pantai karimun jawa nikmat sunrise tiket masuk 10 k parkir motor 5 kpantai luas bangun spot foto toilet sedia akses jalan bagus

kurang untung pas datang pagi niat mau lihat sunrise malah grimis hujanpantainya asri bersih sekali ombak tipis2 khas pantai utara jawapuas sekali habis waktu sini

dengan 10k bisa nikmat view bagus wah worth it sih yang open trip klo free tempat bisa jadi destinasi waktu senggang buat nge chill
pantai sepi adir nya halus bersih

let me start by saying that pantai bobby is an absolute slice of paradise and the highlight of our karimun jawa trip the journey to get there a short and bumpy but fun ride from the main village already feels like an adventure but the moment you step onto the sand every single bump is forgotten this isnt your typical wide sprawling beach its a wonderfully intimate cove framed by lush green hills and ancient twisting trees that provide perfect natural shade the water is what dreams are made ofa breathtaking mosaic of crystalclear turquoise fading into a deeper brilliant blue its so transparent you can see small schools of fish darting around your ankles even before you wade in the sand is brilliantly white and soft a perfect contrast to the vibrant colors of the sea and sky we spent hours just floating in the calm bathwarm water feeling completely removed from the hustle of everyday life its a truly magical place that feels both pristine and peaceful
view bagus pas sunrise

pantai bobby bersih kids friendly lokasi datar asyik banget lamalamaan sini
pantai bersih awat punya vibes apik

get the best sunrise in the beach just spend your idr 10000 if no use travel eo
sepi tenang

biaya 10k per orangview sunrise bagusjalan sini turun naik sudah paving block

jalan pantai bobby penuh hutan cukup jauh daerah duduk kalau kejar sunrise mending pake kendara aja
gak usah naik gunung bisa lihat sunrise

pikna plaa kokosy po 25k a do tego super najlepsze miejsce do snorklingu na karimunjawa na gwnej wyspie ktre nie wymaga wykupienia wycieczki nie widziaem wypoyczalni kajakw a szkoda bo mona by byo atwo dopyn do pobliskiej wysepki bylimy popoudniu i woda bya bardzo pytka nawet kilkadziesit metrw od play
pantai andal lihat sunrise

sunrisenya polll mantapp
pantai bersih viewnya bagus utama pagi hari
keren view nya pantai nya bersih

pantai bobby of course salah satu pantai karimun jawa bisa bilang spot fotofoto orang suka ngontenin libur sini dapat banyak ayunanayunan gantung baris pohonpohon kelapa pinggir pantai bahkan juga ayun lokasi di airpantainya cantik bersih of course ramai banyak unjung
ada tidak bagus view di dapatsemua cantik tiap sudut karimunjawa

gorgeous beach definitely worth visiting for the atmosphere unfortunately there are three key arguments that speak against it we were there on the weekend and when the ferry arrived a lot of people came there just to take their pictures making it impossible to relax the water is extremely shallow if you want to swim there are way better options on karimjawa additionally there arent any beachbeds if you want to lay down you need to lay in the sand which is not a big deal but you should be aware of itgreat for taking pictures but for all other aspects there are better options nearby and around the island
pantai aga sepi adeemmm pantai paling fav wkwkwk
nice

nice view and the sea was clean
tebing cakep poll pandang bawah laut jelas banget tebing tambah cahaya mantep butuh tracking 5 menit

salah 1 pantai paling cntik karimun jawaapalagi dr atas bukitnyaviewnya luar biasaga kalah sm pntai2 disekitarnyabaiknya ksini jgn pas air laut pasang krn jln mnuju ksana trgenang
hidden gems

harga masuk 10kbukan tipe pantai pasir tp lebih tebing pandang bagus
kamera ku mampu cerita indah masya allah

we had a very sad feeling after the huge amount of trash and plastic in such a paradise we mentioned this to the people running the place but the answer was that the sea is going to clean the trash i would totally recommend to go to the next beach called alano and avoidthis satu maybe in this way there is more consciouns about the gravity of the situation fee 10k totally not worth itvery sad

tempat enak tenang santuy mata manja pandang bagus banget cobain naik bukit anora trs snorkling tepi banyak wisatawan asing neng kesini
pantai bukit bagus walaupun jauh kota karimunjawa cukup wort it di kunjung

pantai anora karimunjawa pantai banyak spot view surga hidden gem nya karimunjawa 8km dermaga kapal datang pake motor lebih seru krn tuju lokasi jln nya sedikit offroad warungmusholahtoilet tiket masuk 10k orang jual n tukang tiket ramah terkadang monyet hutan jg nikmat pantai

20 minutes scooter ride from main town of karimun to get these views you need to get to uphill hiking took us only about 4 minutes it was midday around 1130 so it was really hot and dry make sure you bring plenty of drinking water to stay hydrated not many shelter or shady area to hide from scorching sunseptember 2024rydv
indah sekali d pantai annora

stunning beach very clean and barely any people entry fee was 5000 rp per person

pantai bersihnyaman buat anak2 ombak bersahabatview pantai gunung keren

ottimo posto per fare una pausa pranzo rilassarsi godere una bellissima vista e fare dello snorkeling il pesce alla griglia davvero ottimo ed abbondante al costo 23 la conduzione dei vari chioschetti familiare e sono tutti molto gentili ingresso e parcheggio all ombra per il motorino a 05 potrete approfittare delle sedie tavoli e sdrai artigianali in legno c un piccolo promontorio che si immerge nel mare dove fare una passeggiata 10 minuti

100100salah satu turut baik karimun jawa

une plage propre avec du snorkelling et aussi du sable blanc des poufs parasol un bar de la musique le soir le coucher de soleil

great beach for snorkeling and watching the sunsetthere is a local beach club with drinks food and at least this time a djeasy to reach by scooter with enough parkingthe entry fee is 10000rp but it is for more than 1 visit limit unknown bean bags and parasol includedthe water is crystal clear and it stays very shallow for a long time

clearly the best overall beach on the islandthe beach and waters are very clean for the entrance fee of 10000 rupieh you get a lot of different seats and hammocks it is very quite during the day most people stay satu besch further west in the evening they play loud music which is something you should be aware of compared to the beaches on the eastern coast of karimunjawa the water is deeper here so it is very enjoyable to swim

best place to chill in evening

une des nombreuses belles plages facile daccs

gak banyak orang indo kesini banyak orang asingbule turut bagus nyaman soal aku suka tempat gak terlalu ramai hehe

the best beach at karimunjawa island

tenang bersih ramah makan enak cocoksemoga depan bayar pake aris uang tunai batas karimunjawa enjoy

best best best but they did not have restroom yet hopefully soon
bagus sekali sunset nya

suasana pantai tenang hampar pasir putih tawan juga nikmat sunset

neta i poca gent perfecte per relaxarse i veure la posta de sol

i liked a lot this beach because it is less crowded and silent compared to sunset beach the water is clear and a bit deeper compared to the other beaches in the island which is great to swim furthermore in the biggest warung in the middle there is a lovely and sweet lady that cooks amazingsells coconut and she is always ready to help the beach is super clean and well keptthe italian family

5k lentre la plage est trs bien entretenue propre grande avec peu de monde quelques stands pour manger boire une coco des tables transats balanoires possibilit de faire du snorkeling parfaite pour le coucher de soleil

magnifiquetonn de voir si peu de monde beaucoup viennent pour le sunset mais sur le crneau 10h 16h on tait une dizaine maximum sur la plage la plus lest sur la plage principale le concours du selfie et des drones fatiguent vite donc nous navons pas regrett de nous loigner

satu of the hidden gems in karimunjawa its so quiet here white sands turquoise clear sea water it also has warong that sells snacks and drink at a bit pricey price
pantai batu topeng karimunjawa sangat bagus tuju destinasi pulau karimunjawa pantai nya bersih biaya 5rborang

bersih harga masuk sangat jangkau cuman 5k teduh viewnya bagus tambah cukup sepi jarang datang turis letak cukup sembunyi
great sunset view

trs joli et encore trs sauvage la petite taxe dentre de 30 centimes d est la bien venue si elle permet de maintenir la plage toute propre

plage propre eau claire et des transats en bamboo pour 5k lentre

plage payante de 5kpersonne alors que lon paye dj 150k dentre au port en tant que touriste pour le parc national je trouve cela dommage de devoir payer en plus
bellissima

spiaggia carina ma l entrata 25k rp una storia esagerata dopo aver pagato l entrata al parco la spiaggia vicina solo 5k rp a ps pi carina e piena servizi ristorantini e lettini con ombrelloni

an amazing peaceful place and the owner of the little warung will remain always in my heart

pantai nya sepi banget d akses motor datang jam 10 pagi msih sepi banget bagus ubtuk viewnya jalan kaki ke pantai tanjung gelam
kalo pagisiang masii sepi gd retribusi kl sore retribusi 25k per orang

datang sini sendiri travel jalan cukup curam batu tulis tiket masuk 25rborang ketika datang ga tugas minta bayar pantai bagus meski ga sepenuh bersih masih cukup awat cenderung sepi ujung pantai ada jalan setapak hubung sunset beach pantai ujung gelam

collegata direttamente a piedi alla pi nota sunset beach solo che qui non si paga il parcheggio questa spiaggia una piccola chicca sabbia bianca silenziosa e alberata offerta barristoranti scarna spesso risultano chiusi o hanno gi terminato tutto permane anche qui la grande piaga del sudest asiatico rifiuti un po ovunque s anche in acqua non meravigliatevi se troverete spazzatura ovunque anche in acqua purtroppo vi pochissima sensibilit verso il problema in questa area del mondo resta comunque una spiaggia bellissima e molto godibile

lokasi sunset baik karimunjawa panorama kagum lokasi teduh fasilitas lengkap dapat musholla tempat bilas free bean bag akses mudah parkir yang cukupperfect

quiet and clean the people are friendly walk up the hill to get amazing water photos not the best swimming beach but great for eating and resting in the shade
panorama view bagus bagi timur karimunjawa
keren

grandissima delusione spiaggia pratic inesistente mare orrendo
pantai karimunjawa antimainstream
tempat bagusss masih bersih

pandang bukit epic
tempat indah pantai bersih duduk ramah

hill with nice views incredible terrible dirty beach full of trash sampah plastic mana mana fee 10k

pantai annora rupa salah satu pantai pulau karimunjawa letak sembunyi akses sedikit sulit lintas jalan pasir gelombang perlu sedikit trekking jalur akses tuju pantai alano

una devastazione rifiuti sparsi ovunque spiaggia non mantenuta

nice place to take some picture from the peak but definitely not for sunbathing

pantai bisa kata jarang kunjung wisatawan padahal pantai ada bukit view nya super cantik
sunrise beach pasir putih pantai relatif sepi masuk jauh dr jalan aspal lalu jalan kampung sdh beton bagi jalan tanah

keren abisssw

kesini buat liat indah laut karimun jawa naik bukit dikit 200 meter pas udh atas lsg ilang capek masuk 10rborg anak kecil ga diitung

sebaiknnya jangan kemari air laut pasang jalan tuju pantai sisi pantai laut genang jalan pasang tutup akses jalan jadi gembur ban kendara rawan jebak pasirnamun umum pantai tarik kunjung ayun gazebo warungwarung sekitar pantai sedia cukup camil berlamalama tempat inijika punya waktu longgar coba daki bukit pandang laut lepas batubatu karang bentuk bukit jadi tempat tidak kalah fotogenik meski capa butuh juang ekstra
hariluk lukminta
nature

pantai annora biasa aja naik bukit deh viewnya bagus karang2 gazebo banyak angin kalo lama masuk angin pernah syuting pake drone sini
nyaman sangat cocok libur
pantai indah motor masuk tepi pantai
bening banget inimah beuh

sayang pantai kurang awat pasir kuning letak belah barat ke utara dr karimun jawa bisa nikmat pandang dr atas bukit

dapat area santai bangku ayun lengkap warung makan khas jajan pantai tarik annora dapat bukit tengahtengah laut daki lihat laut atas bukit olah temu pantaipantai dari beberapa sisi lereng bukit yang mandi pantai saran duduk tempat datang telah pukul 3 sore air laut surut dapat darat baru diagaktengah laut

spot pertama kunjung injak kaki pulau karimunjawa pantai nya unik bersih tata rapi biaya 10korang fasilitas parkir motor mobil luas toilet bersih warung2 jual makan minum sedia area pantai tata rapi banyak bangku duduk kayu ayun banyak tersebarspot unik lain bukit love annora hill buah tanjung kecil view laut lepas tenang sini view laut hijau tosca jernih sayang ujung sini banyak dapat sampah bekas unjung datang padahal sedia tempat sampah moga depan unjung sadar bersih pantai cantik

pantai bagus naik bukit pandang sejuk mata mas2 pandu kmrin nemenin naik bukit buat foto2 kalo mau beli goreng warung tanya harga dulu gaes 15 keping goreng tempe 1 gelas chocolatos masa hitung 50ribu

akses dari jalan utama karimunjawa lalu masuk jalan makadam terus tanah pasir pantai retribusi murah banget sy lupa 510rb masuknyadi pantai tsb bukit naik gak jauh kok bukit jg gak terlalu tinggi tp pandang oke bgt kl dr atas bukit kata guide lokal kalau mau foto bukit baik mulai dr jam12 air lihat lebih biru tp memang seperti banyak pantai karimunjawa garis pantai naik entah krn panas global krn memang sedang pasang tp dpt cerita jg dr ibu jaga warung pantai anora akses jalan lbh tutup pasir angin ombak besar bbrp waktu lalupantainya sepi bersih sy kemarin blm sempat ciblon cuaca krg mendukungoh iya salah satu foto untk akses masuk pantai anora ada jalan batu jg jd perlu hati2 jg dlm kendara

belle plage mais trs peu de fond donc impossible de nager
good

pantai putar pulau karimunjawa mungkin kurang populer tawar pandang pantai laut biru bebatuan karang alami mempesonaboleh jadi mungkin transportasi sini perlu juang ringan jadi pantai kerap sepi lengangbagaimana juga tekad jenak terombangambing gelombang perahu boat sampai kesini tak buat orang mau berkungjung sinipadahal saja juang tidak mengkhiaati hasil berakitrakit hulu nikmat pandang indah pantai annora kemudian

tempat super cozyy nikmatin sunset tidur bantal pinggir pantai suka banget gak terlalu ramai cuma bikin trauma jalan arah pantai bebatuan curam mau ketawa sama nang kalau inget hahaha see batu topeng
terlalu mengada2 tiket masuk 25k

good place to catch sunset at the island compare to the other beach that i visited this beach has the higher ticket fee of entrance but also has good service ex beanbag included and the beach was not to crowdedbut unfortunately lot of mosquitos came out after the sunset confirmed by the lady beach guard just because of the seasonality hopefully i could visit it again and no more mosquitos
mantaap
nan

clean and beautiful beach
pandang sangat alami laut sangat jernih snorkling langsung pinggir pantai

wonderful indonesian

pantai enak main air sama anakanak ombak tenang apabila masuk beach club bayar 25000 per orang

beautiful well kept beach this is a private beach and at the time of writing costs 25k rupiah to enter the area which the beach sits on contains a shaded bar set about 15 metres back from the shore the shore is lined with beanbags and umbrellas get here early before 2 and you may have the beach to yourself as i did as the afternoon progresses more people show up

kata pantai 24jm pesta ria bareng2 tementempatnya nyaman n banyak menu yang tawar di sinigood luck
beautiful escape
tempat sangat indah

insanely beautiful beach the hanging palmtrees turquoise water super soft sand incredible and we were almost alone the entrance fee is 25k per person but you get a nice bean bag so you can relax the restaurant offers all kinds of drinks and food it was a bit expensive in my opinion

senang banget kesinipantainya bersih bening banget buat foto cocok banget pandang pantai juga bukitdari annora ke pantai gosong naik kapalperahu kecil yang mau renang
pantai bagus cuma akses pakai motor susah kalau pakai mobil
di google map pake bahasa thailand sanskerta jadi bingung apa nama pantai

yes please

syahhduuu bangettt pas kesana sore hari cuaca dukung hujan asyik buat tongki tongki alami

pantai bersih tiket masuk 10rb aku kesana bln oktober 2021 pantai nya deket alunalun akan tunjuk arah jalan bagi udah bagus coraspal bagi belum aseli pasir pantaidisana warung jual mie goreng anget kelapa muda kacang metedisana ayun ada video to ngga di upload huhuu tempat solat tempat parkirini aku foto atas tebing asli lebih buagus naik tebing 5 menit aku saranin pake sepatu baju nyaman hehe

tempat bener2 asripantai tenangbirudtg 2x kesini msh ga bosenpgn dtg lagikmrn pas annora waktu nyari sunrise
pantai anora rupa salah satu destinasi wajib kunjung wisata karimunjawa indah degradasi warna laut sangat bagus kita ada atas tebing

pantai harus datang pulau karimunnya
tempat bagus nyaman
pantai indah bersih awat
amazing places wow
bagus bagus buat photography mantap

annora beach is pretty gorgeous it has white and grey sand but mostly grey the locals sell foods and drinks such as grilled fish fried banana mendoan bakwan and kelapa muda coconut there are two bathrooms not really clean but usable you can rent a motorcycle from the locals to ride around annora beach it has swings to play or take a photo sadly the beach is not as clean as bobby beach there are trashes laying aroundbut overall its a good beach for vacation and resting not for sunbathing would recommend it to others

letak dusun cikmas pulau karimunjawa pulau karimunjawa pantai milik banyak ayun cukup unik cukup lengkap pasal pantai punya gosong bukit indah view luaspantai annora letak ujung utara pulau karimunjawa batas pulau kemujan disekitarpantai annora juga dapat pantai yamin pantai kemlokopantai annora milik luas lumayan besar milik 2 pantai pisah bukit simpan view indah pantai annora atas pantai seperti jadi milik orang grup moga jual masih sangat alami potensi pantai cukup besar jadi idola baru karimunjawauntuk tuju pantai annora lapanganalunalun karimunjawa cukup kendara tuju pulau kemujan sampai pulau kemujan akan palang denah lokasi dusun cikmas di denah sebut dapat rute tuju pantai yamin pantai kemloko situ tulis pantai annora

salah satu pantai sisi timur pulau karimunjawa jarak alun2 karimunjawa 30 menit guna sepeda motor pandang bagus pasir putih sayang waktu sini ada warung buka

terlalu jauh pusat karimun datang pantai guna motor mobil tempat asri bisa lihat pantai dengan naik bukit fasilitas pantai ada ayun serta bisa nikmat pantai dengan minum kelapa di jual sekitar warung pantai annora
cukup bagus asik better kalau orang sana lebih ramah jaga attitude

pantai putih sangat cocok wisatawan suka pantai
sunset point
baru buka 1 bulan lalu bersih banyak warung keren abis

buat nyantai2 enak bgt lahklo kesini wajib bawa google buat snorkling tengah dikit spot terumbu kecilsambil nunggu sunset ciblon2 dulu

udah beach club sini jadi nyantai bean bag dengerin musik nyantai biaya 25rborg
sunset bagus layan ramah

trs belle plage
nan
pantai bagus lihat sunset

pantai bagus akses jalan lebih kecil pantai bobby lebih banyak rumah duduk pantai turun tangga lumayan curam tangga pantai bagus banget lebih sepi jadi asa pantai private gitu untuk yang mau gubuk antara batu karang hatihati batu karang licin lumut tajamtajam
gooddd

senang tempatnyakeep it nice and clean
pantai nya bersih dj pakpong istimewa bakal ken sana pagi maseeehh

jalan perlu hati harus tuju bukit dulu parkir kemudian baru turun pantai

as usual scrolling around without maps hell yeah what a sunny monday morning i knew the name of this place by following the woods signs batu topeng beach main road forget to take pictures heavenly mother ocean love everything it was really great day the sun was shining so bright all areas were clean the sky was blue the ocean perfectly turquoise must be satu of the strongest reasons to comeback quiet beach to date my book fantastic
oke
tempat bagus banyak spot foto
bersih nyaman
nan

akses jln perlu perhatikantoilet tdk memadaipemandangan cukup bagussaat sy posting warung buka satu perlu bw bekal efek convid
tempat sangat rekomendasi bila sedang karimunjawa
pantai indah karismatik
kangen
ulu watu karimun jawa

pandang lumayan tp kotor kurang urus bs tingkat
pantai lumayan bersih pandang istimewa karimun the best
bukit keren banget asa raja ampat

stil eilandje niet veel te doen
bagus banget tempa
cari nemo kuyyy
mantap

salah satu spot baik nikmat sunset karimunjawa akses pakai sepeda motor sini cukup mudah

quiet morning beautiful white sand

white sand warm water clean
surga sembunyi

great clean beach and sea for the swimmingakso you can bring a little food to feed 2 kittiesthey are thin
indah alam sembunyi
fantastis
suasana alamibersih sampah plastic

cote hotel plage courte mais sympa avec des pontons sympas
banyak sampah

magnifique mais pas trs adapt la baignade attention aux mduses les jours de vent vous pouvez y accder par lhtel dsert ou par la plage des 2 cts

25 for the beach itself there isnt really a beach full of trash the water though is beautifulhowever if you keep walking through arys place and eco resort and around toward the bigger resort theres a long pier that can be used to get amazing views and to go in the clear turquoise water swam all the way to the old fish shack not much to see under the water but again the water itself is amazing looks like the maldives almost 55
perlu kelola baik cocok buat lihat sunrise

strand existiert nicht mehr entweder ist er nach der einschrnkenden corona politik nicht mehr gepflegt worden oder die bilder und bewertungen beziehen sich auf einen strandabschnitt der jetzt privat ist und zum hotel daneben gehrt der schne strand befindet sich bei den hotels eco casa und arys lagoon ob diese strnde ffentlich sind ist nicht bekannt
lokasi lumayan jauh dr labuh kesini pas sepi sih lokasi wisata mgkin bsa maksimal bersih fasilitas nyaviewnya cantik hias pohon kelapa jejer

pandang bagus

clean beautiful view
pantai indah bersih ombak terlalu besar
indah banget
wow

pantai mas baru mas perawan pantai bahan pantai dgn nama unik pantai pokemon pantai akan segera hadir resort bintang 4 hotel dseason posisi nya tepat bibir pantai barakuda pantai sangat asri banyak pohon kelapa
pantai indah pencil air tenang view nya

this place tries to do a good jobfor the turtle training them to be released in nature againand a place for hatching without predators eating the eggsonly way to reach this is by boat 250k for the 2 of uson the turtle sanctuary you can release baby turtles for 10k eachnot sure about everyone wanting to pickup te turtles for a photo shootseems the animals experience stress by that
sepi asri
mana wisatawan usir di sini

eine katastrophe die schildkrten sind auf einem 10 m der flche eingesperrt um von touristen angeschaur zu werden keine korallen gar nichts sie schwimmen umher und wissen nicht mit sich anzufangen es ist wie in einem schlechten zoo

im writing this review with a painful heart do not visit this place if you care about the turtles we visited hoping that this is a turtle sanctuary since its somehow advertised as being associated with the national park so we thought perhaps this is a real onewe got charged 150k per person for the boat to get there as soon as we got there we saw big turtles enclosed in a net in the ocean in terrible condition obviously sick covered with slimy green growth these were years old turtles obviously old enough to be released even if turtle well being was actually the goal of this place the guide said theyre kept there to show there are two colours of the turtles which well made it clear upfront what this place isthe turtles on the beach are kept in plastic boxes hundreds of tiny ones in satu box kept there until tourists pay to release satu there were dead ones floating in between the alive ones plenty of older turtles kept in these boxes their whole lives for nothing apart from a show for tourists the guideswere lifting them out spinning them in the air showing to the tourists with the turtles being obviously terrified money for releasing a turtle is paid to the boat driving person who obviously has nothing to do with conservationwe left with painful hearts spoke to our hosts on karimunjawa and they confirmed its not a sanctuary its a business eggs are stolen from beaches sold to this place then theyre kept in captivity until tourists pay for the experience of releasing satu this place has nothing to do with a sanctuary it is yet another place in indonesia where nature animals are cruelly used for the financial gains of locals simply shameful

ich war nicht hier habe ehrlich gesagt nichts positives ber diesen ort gehrt eher im gegenteil und dass es nicht um tierschutz sondern eher um tourismus und geld geht und wenn man gegen bezahlung schildkrten freilassen kann ich denke das sagt ja wohl alles

sconsigliamo a tutti coloro che amano gli animali questa esperienza siamo andati in questo posto credendo fosse una specie centro per accrescimento tartarughe e recupero quelle malate o infortunate gestito da personale professionale e attento che ci spiegasse anche qualcosa visto che abbiamo pagato il biglietto in realt ci siamo trovati in una trovata per fare soldi a costo zero con nessuno che parla inglese solo idioma stretto ci mostrano 6 vasche con poca acqua puzzolente piena escrementi con le tartarughe da piccole a qualche stadio accrescimento in pi gli animali piccoli erano centinaia per vasca con poco cibo tanto che si attaccavano a vicenda e tante morte lasciate l a galleggiare in mezzo alle altre quelle pi grandi erano poche con i gusci pieni melma verde dopo pochi minuti ci hanno chiesto se volevamo pagare un extra per prendere una piccola tartarughina e buttarla nelloceano e fare foto e video squallido

au dpart nous sommes contents dapprendre que les ufs de tortue sont rcuprs pour permettre leur closion mais en voyant que les touristes peuvent toucher les bbs voire payer pour les mettre dans leau nous sommes scandaliss il ne sagit pas de les sauver mais de se faire de largent sans se soucier du bientre ou de la survie de ces animaux cest une honte nous comprendrions mieux quil y ait un droit dentre si cela permettait vraiment de sauvegarder les tortues mais pas ce cirque hypocrite ne participez pas cette mascarade
tetas semi alami penyu tn karimunjawa

nyaman pasir putih bersih ombak tenang harus nginap boleh nikmat indah pantai gratis sedia menu makan minum sangat jangkau

mas friend meh rono otw bar bodo gowo opor karo kupat oke boloo
sea is good

can only access by motorbike or walk
pulau cantik tengah laut

pantai bagus sebenernya belah kampung bugismasuk aja gratis masuk kok lokasi ga jauh lokasi pantai inid sana inap resto cafe

the place can only be accessed by motorbike or on foot its a small beach with a short shoreline though this might be due to the high tide during my visit many mangrove trees surround the beach and it is connected to laendra sunset beach so you can take a short stroll along the shore to reach it

good beach to spend on sunset but sometimes in the high season is very crowded
bayar berapa untuk masuk pantai

serasa di pulau pribadi pagi sunrise nya malam dengar debur ombak senang sekali terima kasih pak masduki atas ramah
jalan masuk pantai batu putih gampang tangga belah kanan jalan haus uweli
sangat indah nyaman

nice viewkesana pas sepi serasa pantai pribadi
tempat bagus sekali
hmmm

still under renovation in july 2023 hope this place could be better in the futurecome here for sunrise as this beach is facing east
tempat nongkrong asik

pokok joss pantai masyaallah luar biasa
skrg terumbu banyak rusak terlalu banyak tambak udang
sepi

wild abandoned and a lot of garbage may 2022
adalah salah satu surga karimunjawa

garder des bbs tortues entasses dans des sceaux pour que le touriste paye pour les relcher et vous nous faites croire que grce vous elles sont protges laisser ces pauvres mres tortues leurs liberts et protger plutt les bbs lors de lclosion a cest thique l cest nimporte quoi les bbs tortues perdent leur instinct et ne gagnent pas en force musculaire dans leur sceau ridicule voir mme saffaiblissent tout a pour le tourisme cest une honte vous naviez aucun respect pour les animaux

pantai saat rupa tetas semi alami baby penyu sini laku edukasi kait penyu lepas baby penyutukik minat segera kunjung psa catat lepas tukik bisa laku apabila sedia stok bayi tukik

sumpah tempat bagus banget lokasi pake perahu untuk lebih enak ikut open trip lebih mudah situ tempat tangkar penyu pantai cukup bagus view tarik bapak jaga ramah pokok wajib di kunjung kalo karimun jawa
bagusss cuyyy pandang nya ga nyesel gw tempat

tempat nalar penyu untuk tempat makan snorkeling

tempat makan siang istirahat tour laut karimunjawamenu makan siang ikan bakarsambil tunggu ikan matang bisa main2 dulu sekitar situ

locals who take care of turtle eggs and recently hatched babies im not too sure about the whole paying for releasing the baby turtles but i dont wanna judge since i dont know enough about that i had a great time visiting the place

kanjen beach is located near boby beach this place can reach by boat only you can rent a boat from boby beach for 100kboat this beach is used for sea turtle conservation visitors can release sea turtle hatchling here there is no entrance ticket but you must pay 10khead for releasing hatchling there are toilet and canteen in this beach some activities can be done here like grilling fish enjoying the white sand or snorkeling around the jetty

salah satu spot henti waktu ikut open trip laut karimun jawa taman nasional tangkar penyu tempat lepas anak penyu laut bayar 10rbekor jual makan minum beli pantai bobby utk pantai belum ada jalan darat naik perahu pp 100rb isi 34org pantai bobby jadi ikon tulis taman nasional karimun jawa
bagus banget pantai nyesel banget kalo gak diving karimunjawa

semua pulau karimun jawa bagus bagushanya harap fasilitas mck baharu sayang pandang bagusikan masya alloh cantik bagustetapi fasilitas mck kurang memadaisemangat karimun jawakembangkan pariwisata lebih ciamik aamiin aamiin alloh
bagus dapat tangkar penyu

taman nasional tangkar penyu lepas anak penyu laut bayar 10rbekor tiket masuk 10rb jual makan minum beli pantai bobby utk pantai blm ada jalan darat naik perahu pp 100rb isi 34org video cek youtube erni puspiko

pulau baik dkt pulau jawa msih alami pantai air jernihpasir putih bersih mudah2n duduk lokal dpt jaga bersih segala sampah plastikterumbu karanglimbah tetap jaga adat suku jawa sopan ramah
pantai view oke ciamik kesan kalo kesini

more like a 455 we went there at high tide so the beach is quite narrow but theres no satu there the water was very calm clear clean there s some trash not on the beach itself but in the bushes but not too badthis could be really nice if someone took care of it properly
pemandanganya jossss

from ocean look

eau claire mais plein de dchets et a pue clairement on sest pas baign

plage trs sympa avec des spots snorkeling tout proches accs payant petits warung sur place

very quiet almost no satu good spot to chill

plage tip top bien nettoye et trs bien amnage limpression dtre seuls au monde

awal kagak pikir belum pernah denger nama karimun lama karimun saya tau nama suatu daerah sumatera utara nyata surga ocean crystal begini jawa masyarakat tempat bener bener ram ramah bgt 3 hari 2 malam sini bener bener singkat bgt wishing can back to this heaven very soon

netter endpunkt bei einer runde mit dem moped durch karimunjawa es gibt allerdings nicht sehr viel vor ort auer meer und fischerboote

beautiful and quiet white sandy beach its so quiet i managed to take a little nap here

klo dri jepara nyebrang naik perahu pake motor ga trus kena brp satu motor 2 orang info dong ka
tempat kalau kelola baik sangat tarik saya sini ada fasilitas warung
pantai alami
tempat buat santai asik buat camping
tempat bagus indah tenang asri recomended
nan

pantai syahdu bgtbersih asa milik sendiri tp syng nyamuk byk bgt
bagus banget sih sumpah gak rasa situ udah ber jam jam akses tuju pantai batu putih sangat mudah jangkau dgn mobil motor gratis
pantai masih asli banyak kelola siipp walaupun lokasi pantai jalan kaki turun bukit

bagus belum kelola baik virgin

sini langsung suguh pandang begitu sejuk mata air laut bening bersih kehijauhijauan sangat cocok banget renang ombak tenang jadi sejuk tiada tara akses pantai batu putih hanya jalan setapak sedikit turun bukit kecil meski jalan kaki jadi suasana lebih karna jarangjarang jalan kaki alam bebas begitu indah pasir pantai bersih putih jadi pantai ini tidak mudah saya lupa
pantai bagus cuma sayang blm kelola dgn baik
indah sunset

pantai bagus sekali lohat sunset disanaairnya beningada home stay warung

jangan siangsiang kalau kesini ga cocok kalau sore seperti sunset jalan kesini cukup jauh alunalun karimunjawa pikir pantai oke nyata biasabiasa
lebih cocok sebut dermaga pantai
karen
sangat indah indonesia ku

pantai bagai dermaga nelayan sbnrnya jd memang tdk pasir pantai main juni 2022 bs sj garis pantai makin maju jd pasir tdk terlihatsebenarnya sy mau laendra tp salah ambil jalan harus kanan malah lurus akhir temu dgn tmpt
alami tenang

tempat snorkeling diving banyak terumbu karang bewarna warni ikan nemo nya tempat nya bagus cocok tempat refrensi libur keluarga

pernah coba budidaya udang faname sini sistem karamba trnyata waktu panen malah ikan sumedar
panorama sunset sunset nya bagus air nya jernih pasir pantai nya putih

ratarata pantai karimunjawa bagusbagus pantai gugus pulau karimunjawa sama bagus bagus

dermaga batu lawang golong dermaga cukup besar bagus kapal besar bisa rapat dermaga warna biru selalu ada keliling dimanamana biru subhanallah waktu terlalu lapar jadi makan roti tawar kita bawa ganjal perutbinokuler bisa fungsi lihat pulau seberang sana langsung aja besar lensa agak lumayan batas pandang lihat guna alat sebut kita amat pulaupulau sebut pulaupulau lihat kecilkecil di tempat simpan ibu indah indah nian tempat subhanallah
pantai batu lawang
pantai batu lawang milik akses cukup baik khusus motor pantai lokasi cukup tenang ada biaya restribusi masuk
alami nan asri
cocok bakar ikan

tarik selalu ngangenin
pantai kanjen punya pasir putih lembut air nya hangat ada konservasi penyu
salah satu tuju wisata bahari karimunjawa sini konservasi penyu cocok memang pasir pantai nya lembut air nya hangat

wonderful natural view
pantai kanjen

pantai bersih jernih tambah tangkar penyuakses perlu naik boat tidak banyak orang tau bagaimana tuju lokasi initanyalah duduk pantai legon lele pantai bobi cara tuju tempat iniserasa pantai milik sendiri
tugas ramah tempat bersih bakal banyak ajar tempat

must visit this place its has sea turtle conservation site you can realease baby turtle to the wild here i recommend to visit at sunset time the ligth combined with the beach and forest just magnificent
pokok keren
pantai sangat alami jarang turis datang recomended orang ingin nikmat pantai tenang

keren2 pantai karimun
pingin banget kesiniiii
perfek

jolie plagepetit bar pour se rafraichir ou prendre un snack
labuh nelayan harus nyebur kalo naik perahu

compare to the other area in karimun jawa i can only give 3 start for this beach
pantenya bersih dn laut jernih pandang sangat sangat natural
nan
tempat msh alami msh tradisi adat

sunset nya indah kalo

quite a small beach and nothing much to sea
so beautifull

dapat inap khas suku bugis sini rumah panggung tapi jalan tuju pantai masih jalan setapak

vi visit this kanjen beach for releasing baby turtles we took a small boat off from lele beach and the journey took about 10 15 minutes the view was great the water is crystal blue clean area and not so many visitors a quite place where you can just relaxing and enjoy the view of the beautiful sea and land
tuju wisata

kawasan adalah zona inti taman nasional karimunjawa jadi obyek wisata batas lokasi dapat lindung telurtelur penyu ruang khusus hindar predator jika untung wisatawan melepasliarkan tukik laut sama penjagapantai jadi salah satu pilih penyu darat pasir halus hangat minim predator daya dukung lingkung rendah akibat sistem das sangat sempit wisatawan pasir halus dapat buat istana pasir d

taking nap under the trees is super relaxing
buat nyepi
pasir putih takjub

pasir putihpantai nya cukup luaspemandangannya bagusjangan kesini pas musim angin timur mulai bulan juni september gelombang tinggiair pasang siang hari
karimun jawa no 1 ini

quiet place for relaxing beach

dont waste gasolinetime going here

tempt sejak kecil lepas lelah menihat sunrise mancing renang

the turnoff to the beach is small so be on the lookouttake anti mosquito cream as you will be attacked by them when you stopit is a short walk down to the beach you will pay 5 000 idr for parkingthe beach has beautiful white sand and there are many places to snorkelthere are many places for you to take photos so dont forget your camera
lovely
pantai sgt cocok buat snorkling santai barmain air laut dgn pasir putih sgt bgs dgn pandang sgt romantis

pantai masih sepi bebas pandang laut biru untuk renang

pantai adalah dermaga kecil perahu nelayan suku bugis bibir pantai coba dayung arah laut kemudian 50 meter lewat karang gosong spot snorkeling tarik meski itu anda ketemu kawasan terumbu karang rusak kawasan masuk dalam zona rehabilitasi sewa perahu jukung nelayan bisa temu spot snorkeling tarik
kalo saya tempat kurang worth it

love this place
cocok sunburn

tunjuk jalan kok ndak jelas kalau mau kesini paham dulu rute soal tunjuk jalan nya minim warga
buah pantai indah keliling tebing batu angkat proses geologis gradasi hutan mangrove pandan hutan hujan tropis padang ilalang sangat indah jalur pantai susur sangat sulit akan tetapi sangat indah

cenderung sepi bukan spot snorkling
eksotik
pantai tenang suka kesini kalau ken nga ngapangapain
masuk pantai bayar 5000 anak kecil gratis pantai nyaman buat tidur enjoy the day

datang pagi set 6 harap bs dpt sunrise benar indah sekali
pantai belum ramai unjung waktu kesana sedikit unjung lebih enak private tempat memang jauh pusat kota jalan begitu mulus pas di pantai wow sekali super sekali pandang bersih pasir putih

prachtig zand strand met een hoop schommels ze hebben wel bedjes maar die zijn van hout na 10 min liggen doet je hele lijf pijnop de meeste stranden hebben ze geen ligbedjes kunnen ze hier niet erg jammer

pantai alano pantai pertama aku kunjung saat dateng parkir motor atas lalu jalan kaki bawah panjang jalan mau pantai aja udah amazing masyaallah indah banget pantai lumayan sepi aku dateng hari jumat
pantai nya bersih kalo pagi agak sepi jadi kayak private beach gak perlu sewa tempat duduk masuk bayar 5000 kayak nya lupa

bellissima spiaggia tranquilla un paradisoa disposizione sdraio legno e ombra delle piante

hidden beach karjaw tepi jenak ramai karjaw kala high season pantai nya sepiii cocok buat orang introvet ken nikmatin pantai ga crowded jarak pusat karjaw 25 menit worthed banget buat bengang bengong

rustig en mooi strand

beautiful and quite beach which is the main argument for visiting since for swimming and snorkeling there are better options

cobran 10000rp por persona es una playa muy agradable y tranquila con poca gente tumbonas de madera hamacasagradec que no tuvieran msica hay un pequeo warung donde venden aguarefrescos y noodles el agua cristalina y la plata muy limpia
asa kek private beach sana pagi

satu of the most beautiful beaches on the main island a quiet palmlined beach with no trash tip be quick for a cool bintang beer
harga masuk pantai 5k sangat sangat worth it pantai bersih tenang tidak banyak orang
paradise

pantai nya cukup pencil jauh pusat kota tp pasir nya putih cukup jernih air pantai nya kemudian sarana buat ganti toilet jg warungrekomen buat cari pantai tidak terlalu ramai butuh tenang

beautiful beach and well kept clean and lovely ambiance please keep it in this way
pantai sepi bersih

the best beach in karimunjawa the best place for camping the family who runs the business and takes care of the area is very nice

unfortunately the shoreline was full of plastic rubbish where we set up the middle part of the beach looked cleaner i dont mind paying an entry fee when the beach is maintained but this was too grotty for me its a shame because if clean it would be idyllic we didnt stay long and wont be back

sepi banget akses jalan susah better naik motor aja tiket masuk 5rb banyak view kapal must go bener bener santai sana hidden gem banyak bule drpd lokal sana even weekend

spiaggia idilliaca a nord est dellisola raggiungibile facilmente con il motorinole sole 5000 rupie biglietto giornaliere valgano uno spettacolo naturale assicuratosdraio legno e posti per rilassarsi sono gi presenti nella struttura il personale molto cordiale e c la possibilit ordinare bevande o cibo cucinato sul momento
fantastica

a hidden calm and beautiful beach saat datang karimun tanggal long weekend semua inap penuh nyata justru alano sangat sepi benarbenar cuman bule tau a virgin beach pasir putih bersih air tenang biru mudajika karimun wajib pantai karena benar2 banyak tau jalan memang cukup jauh 30 menit drai pusat kota percaya parkir motor mata puas pandang

kinda chill and good for sunbathing here however its cloudy and rainy when i visited this place ticket is 5kperson open from 7304pm only you need to walk down to the beach from the parking area recommend visiting anora beach as well while visiting this area
bagus tidak terlalu ramai

tempat enak buat rebah siputih tp galak cuma nggonggong aja klo udah kasih makan nggak nggonggong

very very very nice beach5000 rupees entry fee is well worth ithas a spot with lots of clown fishes

super schner strand sehr sauber und ruhig die betreiber des kleinen lokals sind sehr freundlich und das essen schmeckt super
asri sepi kelola ada justru jadi daya tarik sendiri lebib suka sini karna sepi

dont come herekulit alami gatal2 akibat masuk air pantai alano nyata air cemar tambak udang parah beri tahu jaga pantai plus masuk bayarmohon tindak lanjut sangat bahaya sehat wisatawan
sangat rekomendasi banget kunjung wisata karimunjawa pasir putih bersih air laut jernih masih asri tidak banyak tamu cocok buat destinasi rileks pikir

pantai cantik gak terlalu ramai 25 menit dermagamasuk bayar 5000 warung toiletkesini hibur diri

trs belle plage bien entretenue top pour faire de la baignade farniente snorkelingparking mototres bon moment y passer

einfach nur traumhaft da kommt man nach einer fahrt durch dieses unscheinbare wohngebiet pltzlich an diesem strand raus auch ganz gut zum schnorcheln allerdings muss man ewig weit gehen das wasser ist sehr flach

spiaggia paradisiaca disponibili lettini tavoli e sedie in legno ci sono tante altalene anche nellacqua c anche un piccolo punto ristoro dove rinfrescarsi con una bella noce cocco ingresso 5k
keren

la mejor y mucho mejor que su vecina annora es una muy buena playa que dependiendo de la marea cambia tiene servicios bar comidas mesas hamacas columpios lavabo pero lo mejor de todo son los peces payaso nemo no es necesario contratar una excursin de snorkel verlos los tenis prximos a la playa y marcados con postes con la senyal nemo spot
tempat bagus bersih awat tiket masuk murah cukup sepi cocok buat lihat sunrise kalo sana jaga bersih temanteman

5k entrance with satu shack and a toilet the beach itself is clean the surroundings pretty full of trash clean calm transparent waterbetter to come in the morning or mid day first thing better light and sunshine

pantai sepiiii banget anginya sepoy sepoy warga lokal ramah bngetttt sayng akses masuk masuk hutan recomend sedang mencri tenang ombak besar masuk 5000 orang

5k entrence fee normal amount for most kept beaches in karimunjawa beautiful area lots and lots of swings
luar biasa pantai indah pernah kunjung pasir air bersih sekali ayun manamanapengelola baik ramah wc suasa tenang

sehr ruhig und abgelegen sehr schn eintritt aktuell 10000 pro person wahrscheinlich gilt dieser preis fr auslnderbei flut ist ein groteil des strandes vom wasser berspltwir konnten keine kokosnsse kaufen
pantai bener2 indah banget sembunyi ga banyak datang bersih banget klo naik mobil jala sempit better naik motor kalo kemari parkir atas kemudian jalan turun pantai sumpah indah raih banget
tenang damai pas sepi kesana

recommend for sunrise

posto carino x prendere il sole il bel mare 1 altra cosa
sepi cantik tp kurang nyaman sama sampah pohon2nya jatuh pantai

la plage est sympa mais sale rien voir dans leau beaucoup de bateaux de pche et de casiers sur place
nan

cool place and litterly no satu there so you got the place for yourself
indah bgtt bersih

i visited this beach on sunday around 10 am and it initially had 2 visitors and theyre all foreigners its so calm and windy that day no satu said a thing for a long time haha its the perfect place to chillax the cleaning fee is rp 5000 no parking fee i bought a coconut for rp 15000
datang kesana pagi2 tempat sepi angin sepoi sepoi minum kelapa muda baik

compared to anora beach alano beach is clean alano beach is recommended for rest fee 5k use to cleaning beach

la playa mas bonita de karimunjawa queda un poco retirada a una media hora en scooter pero el viaje vale la pena hay que pagar una pequea entrada como en cas todas las playas de la isla tiene bar y hamacas

nuestra playa favorita de karimunjawa muy tranquila y bonita con sitios sentarse y tomar algo

una delle pi carine dell isolaci vuole un per arrivare dal porto ma ne vale la penacercano tenerla pulita come non succede in altre spiagge

this was a real experience the beach was clean and you can swim in the beach and great swings white sand and coconut tree and beautiful sunset this is a must

very nice beach good for swimming and they sell cold beer as well

aprs avoir visit pratiquement toutes les plages de karimunjawa cest ici le meilleur compromis facile de se baigner profondeur trs vite guinguette avec fauteuils sacs bien agrable ambiance sympa accs relativement facile en scooter
tempat nyaman buat santai buat kalian mau jetski sini menyediakann sewa jetski kano adaaa

klo pagi pagi jangan tanya indah banget kalau dateng langsung air bersih jernih pandang behh

habis waktu sunsetan sini dapet sempat foto pohon kelapa jadi icon pantaiselain sempat main volly bareng warga seru banget ramah2harga makan variasi mahal siap uang cash

jolie petite plage pour le coucher de soleil entre payante 10 000 roupies on peut faire du snorkeling attention au poisson qui mord il y a des warungs pour manger ou boire un verre

effectivement cest le spot pour un coucher de soleil
must try

nice clean beach
spot foto baik nikmat sunset

cafe pinggir pantai dikarimunjawa suasana tenang adem layan nya oke sekaliditambah ditemenin pacar yang ganteng bikin seru obrol
bagusss sangat indahhhh

c tait une belle plage mais maintenant ils ont du travail pour lui redonner son aspect agrable

even though this could be a nice location you can certainly skip this beach its dirty and the small kiosk is broken down
the baldys

eigentlich ein schner strand leider wird er nicht gepflegt und ist voller mll
pantai bagus masih baik pancur sesuai nama

unglcklicherweise wird dieser strand nicht mehr gepflegt und der strand sowie das meer sind voller mll
cedera or pulih cedera cocok fisioterapi sini klinik mitra medika abadi rawabadak

sunrise spot reachable by motorcycle only
pisang goreng enak

i was in pancur beach on 02142025 the beach is beautiful since it is still low season people are doing maintenance to the facilities and cleaningon the beach there is a kiosk where i could eat some good fishon the beach there is a gentleman who can guide you in a really exciting snorkelinghe knows every little detail of the beautiful coral reef and the clownfish seem to recognise himthe clownfish kiss was really excitingif satu day i return to karimunjawa this beach will be the first place i go
pantai indah bersih

the perfect place for an introvert like me

riipumatosta plussaa ranta tos siisti ikv kyll kioski oli tnn kiinni
tidak sengaja mampir pantai pancur lambat bangun cari sunrise pantai bobby tinggal rombong akhir henti mampir pantai pancur dapat momen sunrise

der strand ist wirklich sehr schn und perfekt zum schnorcheln und um den sonnenaufgang zu gucken der strand wird von jawa sauber gehalten welcher am strand bilder malt und uns eine wunderschne schnorcheltour gegeben hat ich kann diesen strand und einen besuch bei jawa nur empfehlen

jawa is an amazing person and gave us a snorkeling tour today at the beach he showed us several spots where to find nemo fishes the experience was amazing i really recommend this beach and jawa if you want a nice experience the beach is clean and calm wonderfull for people who dont want to go to touristic places

great beach it is being kept clean by a fantastic guy called jawa he also does snorkelling trips at the beach worth visiting
so nice

awesome view to see the sunset
couch de soleil magnifique
pantai bersih n bagus

very pretty beach as well as the adjacent ones leftmost tanjung gelam is more for waterspots and photoshoots sunset beach is for the sunset and eating and batu topeng is a great place for chilling out and swimming as the water is deeper here theres also a volleyball netyou can walk between all three very easily the beaches are super clean and have all the necessary amenitiesin september i found them to be almost empty during the day even on a saturday but they get busier around 3 onwards as sunset approached
bagooozz
pantai indah bersih salah satu spot baik lihat sunset

pantai sunset beach salah satu pantai karimun jawa bilang salah satu spot foto turis pohon kelapa miring antri foto aja panjang banget umum bilang pantai ramai banget jamjam sunset di masa liburanuntuk pantai sendiri cantik banyak karangkarang juga bisa pakai buat duduk bengong spot foto alternatif itu juga ada banyak cafewarung merchant yang sedia sewa kanowater sport

keren banget sumpahsayangnya tinggal sunsetnya
the magic of karimun ajawa

view keren pantai dangkal kapal sulit sandar jadi main tengah makan siang dsini ikan kuning bumbu bakar joss mantab ikan daging tebal sambal enak
pantai sangat amat indah termimpi2 akhir datang untuk dua kali wow sungguh indah air laut surut lihat pasir timbul sangat amat luas
banget kesini lagi
pulau view indah pantai pasir putih air jernih sedia beberapa fasilitas warung toilet mushola

the best beach in karimun island my friend really enjoy and happy
bagus pulau pasir air dangkal
wonderfull
best

masya allah betah bgt dsni pasir putih lembut airnyaaa buwiruuu bening
betah berlamalama pulau pantai pasir putih luas ombak tenang
bagus
salah satu pulau baik

salah satu tempat nikmat sunrise pulau karimunjawa
meski akses masuk terjal dikit bagus pantainyasyg pojok selatan bnyak tumpu sampah botol2

access road to here is quite challenging for motorcycle but the place is nice

plage gratuite les grantes nous ont fournies un tapis pour poser nos serviettes il y a beaucoup dalgues nanmoins la plage reste bien entretenue grce un monsieur qui la nettoie joli spot de snorkeling et de lever du soleil
cest hyper sale

they claimed to be the first beach that has been opened in karimunjawa the coastline is quite narrow its a good beach with white sand and turquoise clear sea water but thats all nothing special compared to other beach
sangat nyaman bersih tenang

the best beach with the best guy jawa who is so so welcoming and lovely a must on this island

mungkin pantai dekat dr labuh dgn spot sunrise masuk gratis warung tapi kurang bersih banding dgn pantai2 lain karimun

really great beach hut serving some excellent ayam ikan fresh juice etc reusable metal straws lovely fresh sambals so good we revisited perfect lunch spot cute beach can swim out to snorkel with nemo long tailed macaques

plage tranquille les propritaires sont adorable le monsieur a le sourire tout le temps sa femme est une excellente cuisinire
kalau karimun wajib banget kesini pantai tenang banget aku dateng pas pagi cuma aku sana padahal hari minggu maaf waktu ga beli kafe

amazing place trs calme personnel trs gentil et accueillant je recommande fortement

magnifique plage elle est plus proche de la ville lentre est gratuite il y a du wifi et on y mange trs bien surtout les nouilles sautesnous avons largement prfr celle ci bobby beachnous y sommes alls un samedi aprsmidi et il ny avait pas grand monde le grant de la plage prte gratuitement des matelas et loue des masques et tubas de snorkeling pour 25k il nous a mme accompagn pour nous montrer les meilleurs spots de snorkeling

rekomen bgt kesini buat nikmat sunrise ala karimun btw tempat enak gampang akses cuman minus kotor sih tp tenang gak ngurangi indah tenang biaya free

sauber familir gutes essen gute preise
bagus sunsetnya pasir putih bersih makan warung jangkau tempat wisata

pantai landai bersih pasir putih air jernih tambah warung2 santa nikmat sunset
salah satu pantai luar biasa pulau karimunjawa pasir putih bersih air laut jernih lebih bagus pantai bal dapat pribadi
nikmat sunset cuaca cerah

great musics here and good vibes

very beautiful clear water good drinks

no es exactamente sunset beach sino justo el mercadillo que hay a su entrada espectacular nasi goreng lo lleva una chica joven super agradable y simptica hay cervecita ice coffe a pie de playa hamacas qu ms se puede pedir el mejor nasi goreng que he probado hasta ahora gracias
lokasi nya mantap banget buat sambut sunset dinsore hari kako mau kesini agak lama karena nyaman tempat

perfekt um den sonnenuntergang anzuschauen

des amnagements plutt ddis au tourisme mais un lieu qui a su prserver la magie dune plage superbe sur karimunjawa
yaah okey laah okey okey boleh

best sunset karimunjawa wajib kejar sunset sini indah banget

ruhiger strand mit musik toiletten verpflegung und palmenschaukelkein eintritt

gemtlicher ruhiger strand nettes warung mit freundlichem wirt angenehm um bei shake muda oder bier das meer zu beobachten sehr gutes preisleistungsverhltnis strand wird gereinigt

most karimun visitor choose the famous bobby or karina in the north but i prefer this beach the first freeentry beach on southeast side of karimun jawa island the entrance is like going downhill until the parking space and then walking downstairs to the beach area there is only satu restaurant with quite good playlist if you are lucky you can connect to their wifi i think their highlight menu is fried pineapplei visited this beach twice for lunch and sunrise view since it was weekday there was less people its like having the beach for yourself when its getting crowded then the time to leaveit is a swimmingsnorklingkayakingpaddling spot so you can enjoy those activities here you can find another hidden beach in the north just next to the corner there is a path between the rocktoilet is available next to the restaurant
nice spot for photo

pantai cocok lihat sunrise biaya gratis
bagus banget sunrise nya
sepi kayak pantai pribadi

la playa est muy sucia llena de plsticos y botellas y el agua sucia tambines una pena que no cuiden las playas
pantai emang bagus sunrise tp bersih kurang udara sini sejuk

the coastline is shorter compare to other beaches that i came on the island but have a nice sunrise view since we came too early at eid moment the bar not open yet btw the entrance fee is free

akses jalan tuju pantai cor betonmudah aksestapi sayang kendara bisa turun pantaipantainya bersih ombak tenang nyaman buat main sama anak2the best hidang kafe pisang goreng beda yang
best satu

air laut bening bangetpasirnya bersih spot foto lumayan banyak ayun pohon kursi kayu view laut gunungdi bagi kursi kayu viewnya cakep banget sayang butuh ekstra hatihati buat nyampe bagi kursi kayu akses jembatan kayu udah lapuk banyak paku cuat lewat batu karang
tempat nyaman kontemlasi udara segar pantai bersih pokok joss dah

bagus bgt pantai aman bgt buat anak2

small place small island but it has a beautiful scenery but there are just 2 toilets only

pantai cemara besar salah satu spot paling keren buat hobi foto foto sini banyak banget spot bikin aura jadi lebih gantengtempatnya bersih paling pas buat istirahat isi perut mulai keroncong habis snorkeling next bakal kesini poko
istimewasurga nya karimunjawa
bangga indonesia mohon rawat baik tetap lestari
pulau kecil tempat indah istimewa

bibir pantai nya panjangdan putih
tempat cocok buat makan siang

nice spot for sunrice fresh air and good view wonderful place
rata rata lokasi karimun jawa bagusbagus

pantai pulau kecil ada wilayah air karimunjawa pantai air laut jernih sangat indah
cakep

bagus banget best time kesini jam 36 sore magical banget sunsetnya

pasir halusbanyak kedai makananbisa main main air banana boat kayaking jetski

biar foto berbicaracantik sekali sunsetnyabyar masuk 20rbsayangnya harus order t4 dudukbanyak pondok jual makananwajib belanja klo dudukkelapa utuh 25rboke harga wajarview nya cakep bangetdisini jg banyak nyediain kano banana boat dllklo sy sunset beach cakep utk sunsetpas posisinyausahakan datang pas cuaca cerahklo mendung sunsetnya gak kliatanparkiran klo karimun jawa gratis senang sekali warga jabodetabek disinimakanannya jg golong enakgak manis
lumayan bwt nyunset watersport jg
pantai sangat bersihhtm 10k

some parts of the beach are full of plastic and random shacks that totally ruined the charm of this beautiful place it mustve been a paradise before people took it over but i get that for many its a way to make a living so i dont blame them and i must understand their reality still it looks pretty sad the nature itself is beautifu and a color of the water is magical the amount of trash is also kind of shocking i wish the indonesian government would do something to protect this amazing place because it is special nature is your real treasure

pantai ter konekting ujung gelamlumayan sepi banding ujung gelammemang bagus nikmat sunsetworthrekomenmasuk lalu pantai ujung gelam bayar 10rb per orang

hidden gem karimun jawa musik lite dance and beaches sedia jg lite bite food kelapa hijau n beers sesuai dgn nama menikmatin sunset sini saran guna motor kemari kalo mobil perlu gardan depan balik nya tanjak curam

this place is wonderful as well as to get a sunset such as its name it has a nice atmosphere and always has a comfort feelings around but as usual indonesian are still lacking at how do they maintenance things such trash luckily the trash at the sand beach was less noticeable sustaining useful facilities and awareness about many of stagnant water that causes mosquitoesthe best way to enjoy those chilling atmosphere those splash of ocean water and bird chirping is when the beach is not that crowded my fams are lucky that we arrived at the right time and date910

you can rent a mat here and enjoying the view its comfy and quiet before 3pm a lot of snack and softdrink here good place to visit no ticket fee
pulau karimun jawa

aku kesini jalan sedang baik pantai terlalu bersih mungkin karna baik pantai nya kecil

i visited this place by walking from near the dock of karimun island its pretty far but still managable the beach was just destroyed by the wave days before nobody was there besides 2 locals who managed the small store there and they were cleaning up the beach the beach was so dirty so many trash was there when i visited june 27th 2022 its a small beach but because it was so quiet it feels so cozy there is a small stream that flows to the beach i guess thats why they called it pancur beach i believe it might be way more beautiful before it was hit by huge waves anyways i saw a biawak there

i wanted to give it satu star but i have some hope that it will be returned to its original glory the beach is strewn with trash and looks like its been abandoned it has so much potential with better management
koordinat sunrise karimun jawa

certainly not satu of the most beautiful beach in karimunjawa full of boats and mosquitoes

pasir putih view sunrise sungguh indah saran kesini pagi sepi banyak orang datang ada jaga meski tempat beli tiket masih tutup sini biasa ada pesta pantai kalau malem sayang kotor habis ada acara malemnya
tempat baik utk sunrise

pantai belah timur pulau karimunjawa enak di pagi hari panorama sunrise
juorok bgt pantainyaaaaa

beach is good with the hill view but still not well maintain and dirty around the area the road to reach is only by walk or motor bike
tempat bagus acara grup sayang akses masuk susah depan mungkin benah akses lebih datang lebih banyak unjung
sunrise area

keren banget bbrp minggu kemarin buat acara mice sinidan view nya jg langsung laut
milik pandang indah

belum masuk masa sunset panorama tetep bagus konon kata pandu sunset baik se asia tenggara
kesini sama tim visit karimunjawa

nice beach with lots of restaurants prices elevated coconut 45k lots of touristswater quite deep quickly i would rather recommend alano beach
bagus sekali
good view

pantai indah pernah kunjung pantai adem banyak pohon bersih tak sampah biaya masuk cuma 5000 per orang air nya bening bgt ombak sedang view nya ajib banyak warung tp harga lumayan turut sewa kano jetski kalo mau sewa makin sore makin ajib sih pandang

as the name suggests this spot is a mustvisit for sunset lovers picture this a stunning white sandy beach with shallow waters and calm waves perfect for a leisurely stroll along the shore the view is absolutely breathtaking as you watch the sun slowly dip below the horizon painting the sky with vibrant shades of orange and red its a magical moment that will leave you in awe
sangat pesona
pasir putih nyaman main anakanak

a great beach and a breathtaking sunset water is crystal clear just be wary of the biting fish near the corals some small fish are territorial and dont hesitate to bite doesnt hurt feels like a pinch but it will suprise you
una playa tranquila y preciosa

pantai bersih bapak ibu punya rumah ramah ngecamp izin dulu bapak ibu fasilitas kursi santa gazebo toilet musholaada resto pesan makan minumada inap bagus bersih

ruhiger strand leider hat es viele schwerlklumpen am ganzen strand
sangat tenang nyaman santa
pantai bersih dgn ombak kecilcocok untk santa
tenang senyap
loved it

enak kunjung pagi sunrise

they try to clean only 5 meters of the sand and throw all the rubbish just at the edge of the forrest very undermanaged education and public rubbish collection are badly needed they are asking even under these terrible conditions for 10000 cleaning fee otherwise you can buy there some beer for 60000 the place is great for a sunrice watching but just after 5h30 a lady will come to take your 10000 rupiahs

didnt eat or drink just had this beach to myself for 2 days so far maybe gets busy on weekends walked from town paid 10000 rp which seems the norm on karimunjawa cannot complain good spot to read my book and chill

we were there in the afternoon beautiful beach and seashore scenery clean beach a nice photo shoot spotit is not too wide area but there were only 4 of us and another couple before us feels like private beach theres an entry fee of rp5000pax which the local community charge for maintaining and cleaning the area which was worth the moneyno food stall nor restaurant there
bersih pantai layak di kunjung
viewnya bagus

spiaggia a pagamento 10000 rupie a persona credevo che i soldi dati da noi turisti occidentali servissero a mantenere il luogo in cui vivono e tutti noi viviamo pulitoquello che invece mi sono ritrovata dinnanzi dietro al velo perfezione paradisiaca un mare cristallino dietro alle sdraio agli ombrelloni e bar stato un mare plastica seppellito sotto alla spiaggia a giusto 2 metri stanza da quella attrezzatabottiglie plastica zaini plastica ciabatte gomma sacchetti plastica nascosti sotto la sabbia candidaquesto stato lo scenario visto e rivisto in differenti luoghi dellindonesia facciata perfezione che nasconde assenza rispetto per il loro paese meraviglioso e per tutti noi che viviamo in questo pianetarifiuti gettati per le strade per i boschinon oro tutto quel che luccica molto spesso non altro che plastica

nice place beautiful scenery
nice secluded beach
pantai tersemvuny8

selalu rame kalau mau dapet foto bagus fateng lebih awal dri trip lain
sini pantai nya baguss banget bersih

peccato per la plastica e nonostante sia ancora una delle meglio tenute ne pienaio ho visto solo turisti australiani eo europei a pulire io compresa dicono che la piccola tassa che si paga per entrare nelle spiagge a karimunjawa aiutano i locali a tenere pulite le spiaggemah
pantai bagus banget bersih pasir putih lembut ombak tenanglandkap nya baguus deh harga tiket masuk idr 10000

ein schner strand jedoch wie bei fast allen gepflegten strnden auf karimunjawa muss man hier 10k idr eintritt bezahlen es gibt ein wc gebetsraum bzw eher ein gazebo sitzmglichkeiten einen warung der essen u d trinken verkauft und ca 7 schaukeln die gratis sind und teilweise hoch oben an palmen befestigt sind tagsber kann es relativ voll werden und die meisten wollen fotos von sich mit den schaukeln und anderen spots machenweiter drauen gibt es ein paar schne pltze zum schnorcheln und wenn man motiviert ist knnte man auch zu der kleinen vorgelagerten insel schwimmenvermutlich auch ein guter strand fr den sonnenaufgang hab ich aber nicht getestet und abends wenn das wasser seichter wird knnte man auch zum pantai karina rbergehenda ich fters rezensionen gelesen habe dass man ein boot zur schildkrtenaufzuchtstation mieten kann ich habe ehrlich gesagt nichts positives ber diesen ort gehrt eher im gegenteil und dass es nicht um tierschutz sondern eher tourismus und geld geht und wenn man gegen bezahlung schildkrten freilassen kann ich denke das sagt ja wohl alles
kenal ayun ayun pantai pasir putih laut jernih

cantikkk bgtt semua spot foto sini free hihihi klo karimun wajib bgt siniii

nous avons pass la soire danniversaire de ma fille lbas ctait super on nous a prpar un feu nous tions seul nous avons pu faire un feu dartifice que nous avions achet dans le centre ville le grant de la plage tait trs prvenant et nous a laiss la musique ma fille tait ravie
beautiful view
toilet ada air banyak sampah
dapat sunset

traumhafter strand bei ostwindwetter etwas aufgewhltes meer
pantai bersih rapiindah

cantikkk sunrise besttt bgttt kalo sini

playa muy bonita con unas preciosas vistas a la ensenada y a las montaas hay que llegar en moto y la carretera es un poco revirada
jet sky kano warung drone

very nice to see the sunset and many activitys here

turn the sound on see what i show you about this placeyou will never find a place like this

a great place to enjoy the sunset
bagus bgt

pretty cakep bgt bgt please klo kesini nikmat sunset beli kelapa sih best bgt main air foto jugaaaa loveeee

kenal pantai nikmat sunset nyata datang sini pagi oke kokpasirnya halus air sangat untuk main basahbasahan takut riak terlalu besarminusnya banyak semut merah mungkin banyak pohon buah yamalah lebih nyaman datang pagisiang belum terlalu ramai
best sunset pulau karimun
nan

sini pas pasang cocok buat canoeing mungkin next bakal coba jetskinya mending dateng jam 4 sore bisa coba banyak water sport

spot ikonik pohon kelapa miring paling rame buat foto foto salah satu pantai paling oke buat cari sunset banyak sewa kano jetski
sayang dulu abadi fotovideo dulu 2016 asri sekarang asri

destinasi wajib karimunjawa ke karimun kalau kesini sunset nya wow banget

lumayan banget cuman pantai kotor hehe betul waktu kesini udah sore pas pulang jalan gelap pol ada lamputapi overall oke
wajib kunjung pas sunset bagus banget

pantai pasir putih cocok nikmat sunset sedia macam watersport sini segala macam pake dokumentasi
pantai nyaman kunjung rekomen buat butuh tenang jalan pantai ga sia2 lah

fav spot sunset kalo di karimunjawa

pantai tanjung gelam partai bagus bersih ombak nya tenang sewa jetsky kano ada dokumentasi droneada jual makan ringan kelapa muda dllbanyak spot foto bagus pantai rumput laut ayun bagai titik pohon kelapa miring

beach in western part of karimun jawa island have beautiful sunset view acces road to tanjung gelam quite narrow makes it difficult if two cars pass side by side price of food in tanjung gelam is quite expensive i bought 1 fresh coconut for 25k
scenic view nya pohon kelapa miring

pantai pasir putih indah lihat sunset amazing banget woy

nah paling suka pantai mpe 2x ksini bisa main banana boat akses kesini lebih nyaman ketimbang pantai sunset lebih jauh lebih amannnnnndisini banyak aktifitas jetskidronebanana boat kano rolling donut si bocil suka ngumpulin uang mermaid kata diabanyak warung so far kita datangin standar karimun kelapa 25rb goreng 3rb better tanya dulu biar amannah ga enak tuh toilettttttttttsebisa mungkin kl ga pepet ga usah ke toilet deh bayar gitu deh ga layak pake banget kl dar ganti baju bawa kain tutup aja lah

hands down the best beach karimun sore day 1 aku kesana buat foto prewednya temenku hasil oke banget abis day 2 waktu abis snorkling nyantai situ snorkling tipis d tepi pantai ikan banyak so pretty gak nyesel sama sekaliii definitely woll come back
baru kali datang pantai tanjung gelaim nuansa alam nya indah saya pulau bal tiada dua ngak pernah bosan kunjung pulau dewata
sangat wellsayang gak bawa pakai ganti

this beach is actually connected to sunset beach and you can easily reach it by walking along the shore from there however if you enter from tanjung gelam beach there is an entrance fee of 5000 idr im not sure whether this is an official fee or an informal charge the iconic feature of this beach is probably the leaning coconut tree which tilts at nearly a 45degree angle

salah satu spot foto pantai baik ada karimunjawa bila datang sore hari cuaca tidak mendung dapat pandang sunset sangat indah saran sana musim kemarautapi tidak tahu bila datang sana musim kemarau akan jadi pantai sangat ramai tidak
indah banget pantai puas fotofofo pokok
pantai cantik cocok berenanga sama anak2 pasir putih air jernih
bagus bgt pandang
indah sekali pandang

magical beach sih ini jauh kota sangat worth to come kembali kesini kalo kesini pantai bersih pandang bukit sangat manja mata
salah satu spot pantai ayun estetik
anak paling suka kesini maen ayun
alhamdulillah

bayar 10rb simpel toilet aja ga air kotor bangetdi karimun banyak pantai lebih cakep fasilitas umum proper
view nya keren eksotis bersih cocok yang cari suasana tenang jauh ramai

rinduuu pingin baliiikkk
pantai nya cocok buat sendiri
nan
harga tiket masuk skrang brpa

tempat jadi basecamp lama 3bulan karimunjawa

pantai sembunyi si ini tapi ga kalahh cakepp pandang sepi jugaa emang karimunjawa salah satu surga indonesia

after visiting bobby beach i stopped by legon lele and was struck by how quiet it wasalmost eerily so especially when alone the sunrise here is also hard to catch as its blocked by a hill satu of the beachs main features is a sunken ship but the beach itself isnt very clean due to its baylike shape where trash tends to collect and its not cleaned frequently the road to the beach is accessible by motorbike though cars may have a bit of trouble navigating it additionally theres a hill in the area and the local sources of clean water comes from this very hill
pantai cukup bagus kotor banyak sampah bawa ombak

a deserted beach with shipwrecks you cant swim here the water is very polluted from these ships but its fun to explore this place and take lots of photos with graffiti
sejuk masih asri
so polluted
cocok main air renang kotor banyak ranting

pesisir bahan pantai boby fresh muara hutan bakau waspada serang nyamuk sini
pantai legon lele pantai ujung pulau karimun pantai bersih kereen pandang

bilang tetangga nya pantai bobby jarak 5 menit lebih dikit jalan kaki pantai bobby jalan kecil masih banget akses pake motor mobil mungkin ga lebar lebar banget mobil pick up standar bisa terus pantai legon lele fokus pariwisata mangrove betul aku kemaren emang juga lagi teliti itu jadi mampir cuman kurang pantai sepi unjung emang rem kalo terlalu malem kesini nya soal kayak gaada terang jalan buat foto foto gitu cocok kok itu tadi aku saranin datengnya siang aja yah

salah satu hidden gem mah karimunjawa kalau kalian tau nunggalan beach bal seperti ada kapal bengkalai dimuralin viewnya indah deket hutan bakau masih deket jangkau pantai bobby kalau pas gak musim angin barat tempat bersih rekomended sih free biaya masuk

hidden paradise1 pantai campervan turun side byside tendabelum dikelolaombaknya tenang karna telukdasar pasir padatkeras jadi aman lalu 4x4 stdbanyak sampah endap di dasar lebih perhati ada endap hutan mangrove jadi air lihat kotor

jadi pantai kotor yaa kotor tumpu sampah panjang garis pantai jalan becek bangun sempurna akan pantai tinggal tidak rawat kalau amat benar2 pantai cantik loh kontras saudara si pantai bobby air hijau tosca ramai kunjung unjung pantai si legon lele lihat tarik cara sendiri warna kuning yah kuning kaya air kencing jangan salah air pohon bakau perhati warna kuning emas nya unik waktu kesini jalan mengexplore pesisir suguh warna air kuning emas tidak terlalu peduli saking banyak sampah sera tangkap adalah si cantik legon lele sambut dengan wujud diri sendiri beda apa adanyadi seberang pantai nampak bangun macam rumah apung ingat kami kepada ora beach malu moga depan pantai cantik ada peduli peduli warna diri yang beda peduli kuning emas warna air nya kuning emas jaya moga sampah2 jadi hilang pantai cantik

mampir sebentar pasca pantai boby karimunjawa niat hati mau sunrise sini tp pikir krn sepi nyata sepi beneran creepy kalo pas sendiri sunrise dr sini jg tdk terlalu lihat krn tutup bukitikon pantai legon lele kapal karam jd sj ikon sy pantai memang tdk terlalu bersih bentuk teluk sampah biasa kumpul teluk tdk sering bersih jalan bs akses dgn motor mobil ngepres tp kmrn ketemu duduk lokal bawa mobil dr arah legon lele jg sihdi legon lele bukit dapet cerita dr karyawan hostel kalau salah satu sumber air bersih bukit legon lele itu
gak apa apaa

hope that i write this right because i was scrolling around without maps i found this place just couple blocks from bobby beach i didnt mind with how mother nature works i was born and grown up living nearby the oceans someday the seashore is clean and another day would be some rubbishes climate change pandemic as well can be understood tho if the local do take care of course its voluntary kinda stuff see in another bright occasion

morning ride brings me herethe beach looks unmaintainedlots of trashbut still the scenery was beautiful
nan
silently beach

the beach scenery is so so and have many garbage maybe because the eastern wind is hard in may you cant see sunrise in here because the sun was blocked by the hillbut if you want to go to floating paradise and see the turtle conservation you can come to this beach for rent the boat
tempat sangat bagus mancing

a nice place to see sun rise in karimun jawa
kenang bagus
juga keren bangetttt

a wild beach very littered plastic everywhere if someone took care of it beach would be really pretty and it is even hard to walk barefoot through it
biaya 5k
lokasi sunset favorit karimunjawa

hepi sunset baik pas hari pertama pantai inihepi cobain main jetski disinipantai nya sangat cocok buru sunset jadi hampir tiap hari sunset hepi kesinitiket masuk 5 ribu rupiah orang
keren nie
bagus
ikon coconutree sunset baik

mantappu jiwa gorgeous place with a nice soft white sand

salah satu pantai sudut pulau karimunjawa bagus nikmat sunset banyak sewa kapal kano pun gazebo warung deret icon pantai adalah pohon kelapa miring
pantai tanjung gelam salah satu pantai indah karimunjawa pasir putih lembut air laut jernih buat sempurna renang santa main kamu main kano jetsky tentu bayar suasana sini sangat tenang damai

wonderful beach pasir putih langit biru orange senja perlu effort kesini yaa jamin seworthed

salah satu pantai baik karimun jawa spot paling bagus lihat sunset nikmat indah matahari benam bisa main jetski watersport lain nikmat sore goreng stall kecil sembari dengar air laut susur pasir pantai recommended banget bersih
sangat bagus kpan kapan kesini lgi dehhh
tempat favorit cuci mata
pantai begitu indah hampar pasir putih air bening banyak jual aneka ragam makan

pantai sejuk pasir putih sedia sewa jetsky banana boat
view ayun pantai baik karimunjawa

kolam renang raksasa yes bisa renang ke tengah hatihati kulit jd gosong
best spot for sunrise

cakep banget pantai banyak lokal kesini buat foto2 krna banyak spot foto cantik sempetin buat renang senang sekali air jernih bahkan sampe jauh pantai masuk pantai favorit wisatawan sih
view nya memang cantik foto pantai saran sih datang pagi pantai sepi untuk take picture pasir putih air biru jernih view bukit manja mata suatu indah alam harus sangat jaga

prettyy omg but its to crowded when i go here you can play with sand also take a good picture
indah sejuk
pantai wajib kunjung
pantai bersih saran kalau kesini mending waktu pagi biar rame

to get here you need to go down a brick road that seems to lead nowhere but youll know it when you see it its a great beach for kids the water is very shallow with no waves theres swings tree houses and hammocks the main thing not kidfriendly is the usual clientele smokes a lot i just relaxed in a hammock here since id been driving a motorbike all day and it was very peaceful

not a beach for swimming but a sunrise beach it gets crowded really quick but the stall that sells goreng gives you meaning in life
pantai indah biru bangett ayun panjang jadi salah satu spot foto favorit
bagus makan harga jangkau
indah senang
pantai pasir putih

amazing place

quite beach with beautiful white sand and views there is shipwreck which is good for photos object you can going up on it if you find water level is low
nan

white sands quiet wave easy access not too crowd feel like a private beach
kurang awat pantai kotor
pantai indah sekali pandang laguna satu pulau di tengah ombak kecil pantai putih pantai sunrise
pantai kotor sekali akses sepeda motor
dirtykotor foto ambil tanggal 30 juni 2019

jalan tuju pantai jalan setapak tp akses naik motor dgn ban standar pantai punya ciri khusus perahu onggok bibir teluk sayang waktu sana sedang musim angin timur jd banyak kirim sampah tuju pantai
indah alami
pantai baru timur karimunjawa
tempat sepi enak buat santai
natural kelola
asri alami

tempat wisata karimun lama tdk kunjung wisatawan kurang awat padahal sangat kesan
beautifull beach
pantai sepi akses jalan tdk baik

best beach on karimun main island you better go here
nan
perlu perhati perintah kelola
sepi
pantai resor
stunning

nice place for sunrise and hangout with friends

depending on when you come and wind direction in june its sadly full of rubbish yes good view of sunrise if not cloudy be there by 5am road is windy do be careful motorbike access not sure car can get through

destinasi sangat bagus amat sun rise jalan tuju sana bagus lalu motor jauh mukim so pasti bensin jangan mepet2 jalan naik turun pantai pasir putih di belah utara rupa hutan mangrove lebat
pantai indah

In [8]:
df

,title,stars,text
0,Pantai Tanjung Gelam,5,nan
1,Pantai Tanjung Gelam,5,pantai menakjubkan pasirpasir putih good
2,Pantai Tanjung Gelam,5,pantai tanjung gelam merupakan salah satu pant...
3,Pantai Tanjung Gelam,5,salah satu pantai favorit bila karimunjawa ber...
4,Pantai Tanjung Gelam,5,pantai denganpasir putih bersih panorama laut ...
...,...,...,...
715,Pantai Legon Lele,4,stunning
716,Pantai Legon Lele,5,nice place for sunrise and hangout with friends
717,Pantai Legon Lele,3,depending on when you come and wind direction ...
718,Pantai Legon Lele,5,destinasi sangat bagus pengamatan sun rise jal...
719,Pantai Legon Lele,4,pantai indah

In [9]:
df.to_csv('../data/preprocessing/preprocessing_data.csv', index=False)